name: API Automation

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
      issues: write
    steps:
    - name: checkout code
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
        
    - name: Run API Test
      run: mvn clean test -Dsuite=api-suite

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v4.6.0
      with:
        name: Logs
        path: |
          test-output/reports/
          target/surefire-reports/
          logs/
          
    - name: Test Reporter
      uses: dorny/test-reporter@v1.9.1
      with:
        name: TestNG Result
        path: target/surefire-reports/junitreports/TEST-*.xml
        reporter: java-junit
          
    
